services:
#  backend:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    depends_on:
#      - mysql
#    environment:
#      - spring.datasource.url=jdbc:mysql://mysql:3306/zpwj
#      - spring.datasource.username=root
#      - spring.datasource.password=
#    ports:
#      - '8080:8080'
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=zpwj'
      - 'MYSQL_ALLOW_EMPTY_PASSWORD=true'
    ports:
      - '3306:3306'
